export const allSelected = [
    {
        name: 'Aaditya Mahanta',
        username: 'aditansh',
        regNo: '21BCI0046',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Abhinav Dinesh Srivatsa',
        username: 'papaya147',
        regNo: '21BDS0349',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Anuj Parihar',
        username: 'bear',
        regNo: '21BBS0162',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Aryan Agarwal',
        username: 'Axernox_Luxia',
        regNo: '21BCE2173',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Ashwin Ravikumar',
        username: 'E_Lucid_At0r',
        regNo: '21BEC0148',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Dharrsan Amarnath',
        username: 'Dharrsan',
        regNo: '21BCI0022',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Haashir Sanaa',
        username: 'sanaa',
        regNo: '21BCE3348',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Jvnganesh',
        username: 'Jvnganesh',
        regNo: '21BDS0085',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Kanishk Sharma',
        username: 'prokan',
        regNo: '21BCE3649',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'mayhul',
        username: 'mayhul',
        regNo: '21BCE0300',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Nitish Ramaraj',
        username: 'nitish123',
        regNo: '21BCE0220',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Prabhav Mishra',
        username: 'prabhavms',
        regNo: '21BCI0155',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Pratham Mishra',
        username: 'Pratham',
        regNo: '21BDS0133',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'PRERIT RANA',
        username: 'Devrana',
        regNo: '21BCE0226',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Rohan Verma',
        username: 'rohan-verma01',
        regNo: '21BCE0498',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Shivam Gutgutia',
        username: 'shivam.gutgutia',
        regNo: '21BCE2620',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Shreyas',
        username: 'Nimkar',
        regNo: '21BBS0085',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Siddharth',
        username: 'siddnikh',
        regNo: '21BCE3587',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Viraj Shah',
        username: 'Veer1516',
        regNo: '21BCE0577',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Adhiraj Singh Chauhan',
        username: 'Adhiraj11',
        regNo: '21BCE3915',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'akansh',
        username: 'bansal',
        regNo: '21BCE3280',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Aman',
        username: 'Deep',
        regNo: '21BIT0225',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Aniket Chawla',
        username: 'Anni_CH',
        regNo: '21BCI0333',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Arjun Raizada',
        username: 'Arjun_Raizada',
        regNo: '21BEC2404',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Aryan Chaudhary',
        username: 'AryanC19',
        regNo: '21BCE3768',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Ayush Katkurwar',
        username: 'ayush02',
        regNo: '21BCE0856',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'BHAVYA AMBARDAR',
        username: 'BHAVYA14JAN',
        regNo: '21BCE0499',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'D.S.Naveen',
        username: 'DiazOnFire',
        regNo: '21BCE0336',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'dhruv tomar',
        username: 'dhruv_123',
        regNo: '21BML0078',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Girish Murugan',
        username: 'girish0606',
        regNo: '21BCE0182',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Harshita Dutta',
        username: '_harshitadutta',
        regNo: '21BCE2474',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'K.Sriharri',
        username: 'Harri1703',
        regNo: '21BCE3318',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Manav Taluja',
        username: 'Manav',
        regNo: '21BCE3592',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Mohmika Kapoor',
        username: 'MohmikaKapoor',
        regNo: '21BCT0027',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Nakshatra Raghav',
        username: 'nakshatra_raghav',
        regNo: '21BCE2728',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Pradhyumna Kadambi',
        username: 'Pradhyumna',
        regNo: '21BCE0095',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Pratyaksh',
        username: 'poggers',
        regNo: '21BKT0092',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Puja Maheshwari',
        username: 'Pujam2003',
        regNo: '21BCE3172',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Rishit',
        username: 'rishitg32',
        regNo: '21BCE0842',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Sarthak',
        username: 'sarthxk09',
        regNo: '21BCE2748',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Spandan Kumar',
        username: 'SP4ND4N',
        regNo: '21BCE0301',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Sriram',
        username: 'Escanor_123',
        regNo: '21BCE2512',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Srisha Deepak Poddar',
        username: 'srishapoddar',
        regNo: '21BCI0015',
        domains: ['tech'],
        status: 'committee',
    },
    {
        name: 'Kaushal Rathi',
        username: 'techbox24',
        regNo: '21BCT0084',
        domains: ['tech'],
        status: 'core',
    },
    {
        name: 'Nilay Nath Sharan',
        username: 'SubstantialCattle5',
        regNo: '21BEC0784',
        domains: ['tech'],
        status: 'core',
    },
    {
        name: 'Kush Goyal',
        username: 'RoyalPotato96',
        regNo: '21BCE0331',
        domains: ['tech'],
        status: 'core',
    },
    {
        name: 'Arjun Khanna',
        username: 'ArjunSIR',
        regNo: '21BKT0120',
        domains: ['tech'],
        status: 'core',
    },
    {
        name: 'Priyanshu Kumar',
        username: 'mekken',
        regNo: '21BIT0180',
        domains: ['tech'],
        status: 'core',
    },
    {
        name: 'Anirudh Mishra',
        username: 'anirudhgray',
        regNo: '21BCT0168',
        domains: ['tech'],
        status: 'core',
    },
    {
        name: 'Alisha Bnadyopadhyay',
        username: 'alisha0704',
        regNo: '21BCE2569',
        domains: ['tech'],
        status: 'core',
    },
    {
        name: 'BHAVYA AMBARDAR',
        username: 'BHAVYA14JAN',
        regNo: '21BCE0499',
        domains: ['tech'],
        status: 'core',
    },
    {
        name: 'Sankalp',
        username: 'Qualice',
        regNo: '21BCE0830',
        domains: ['tech'],
        status: 'core',
    },
    {
        name: 'Aditya Khandelwal',
        username: 'adityak',
        regNo: '21BCT0164',
        domains: ['tech'],
        status: 'core',
    },
    {
        name: 'Aaron Mano Cherian',
        username: 'RodRedline',
        regNo: '21BCT0066',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Adya Bhalla',
        username: '21BEE0035',
        regNo: '21BEE0035',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'akansh',
        username: 'bansal',
        regNo: '21BCE3280',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Akshat Chaudhary',
        username: 'akshat',
        regNo: '21BEE0019',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Arihant Bharadwaj',
        username: 'arihant14',
        regNo: '21BCT0356',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Aryan Khatuwala',
        username: 'aryan.khatuwala',
        regNo: '21BCE0545',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Devina Chauhan',
        username: 'devinachauhann',
        regNo: '21BCE2684',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Divija Kejriwal',
        username: 'Divija',
        regNo: '21BCT0026',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Diya Ramani',
        username: 'Diya12',
        regNo: '21BIT0392',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Haashir Sanaa',
        username: 'sanaa',
        regNo: '21BCE3348',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Jashandeep Singh',
        username: 'jashan272',
        regNo: '21BEC2339',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Jeenia Gogoi',
        username: 'JehG',
        regNo: '21BEC0302',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Kaushal Rathi',
        username: 'techbox24',
        regNo: '21BCT0084',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Krishnan V S',
        username: 'Krishnan',
        regNo: '21BIT0662',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Mihika Maheshwari',
        username: 'Mihika',
        regNo: '21BCE0198',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Nitish Ramaraj',
        username: 'nitish123',
        regNo: '21BCE0220',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Priyanshi Dixit',
        username: 'priyanshidixit',
        regNo: '21BIT0228',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Rishab Lahari',
        username: 'R.Lahari',
        regNo: '21BCE0330',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Sanah Arora',
        username: 'Sanaharora21',
        regNo: '21BCE2776',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Shreenath Siriyala',
        username: 'ShreeTheTree',
        regNo: '21BIT0190',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Shreyas',
        username: 'Nimkar',
        regNo: '21BBS0085',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'shwetansh',
        username: 'shwetansh420',
        regNo: '21BCE3404',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Siddharth R Iyer',
        username: 'sidd1506',
        regNo: '21BEC0862',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Sumanth Rao Appala',
        username: 'Sumanth',
        regNo: '21BMM0008',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Vaishnavi Rathod',
        username: 'Vaishnavi',
        regNo: '21BCB0191',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Aayush Chhikara',
        username: 'Aayushx393',
        regNo: '21BCE0346',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Adira P',
        username: 'AdiraP',
        regNo: '21BCE2192',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Agrima Tripathi',
        username: 'drop_database',
        regNo: '21BEC2304',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Aishwarya Billa',
        username: 'ab12',
        regNo: '21BDS0010',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Amlan',
        username: 'Amlan',
        regNo: '21BCE2945',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Anshuman Gupta',
        username: 'AnshumanG',
        regNo: '21BIT0271',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Antareep Majumdar',
        username: '21BCE0822',
        regNo: '21BCE0822',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Aryan Chaudhary',
        username: 'AryanC19',
        regNo: '21BCE3768',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Aryan Tyagi',
        username: 'aryan__1703',
        regNo: '21BCE0662',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Asim Nepal',
        username: 'asimn7',
        regNo: '21BCE3888',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Astha',
        username: 'astha',
        regNo: '21BCE0288',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'D.S.Naveen',
        username: 'DiazOnFire',
        regNo: '21BCE0336',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Divya Jagwani',
        username: 'Djagwanii',
        regNo: '21BEE0126',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Harsh Vardhan Shukla',
        username: 'harsh_vardhan121002',
        regNo: '21BCE2236',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Kavinraj S R',
        username: 'kavin',
        regNo: '21BCE0341',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Kinjal',
        username: 'kinjal',
        regNo: '21BCE2666',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Kushagra Gupta',
        username: 'kushagra.gupta03',
        regNo: '21BCE3567',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Pranjal Pratosh',
        username: 'pranjal_pratosh',
        regNo: '21BCE3291',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Samyukta Parakat',
        username: 'samparakat',
        regNo: '21BBT0297',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'SHAUNAK PAL',
        username: 'SHAUNAKPAL',
        regNo: '21BCE2372',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Shravani Rane',
        username: 'shravani_raney',
        regNo: '21BCE2910',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Srinithi Shabad',
        username: 'Srinithi',
        regNo: '21BCE3553',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Srisha Deepak Poddar',
        username: 'srishapoddar',
        regNo: '21BCI0015',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Vidit Kothari',
        username: 'Ramien_Dice',
        regNo: '21BCE3610',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'BHAVANA SINGH',
        username: '21BCE2431',
        regNo: '21BCE2431',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Siddharth Bhardwaj',
        username: 'siddharth.17',
        regNo: '21BCE2001',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Tanvi Yadav',
        username: 'tanvi.s',
        regNo: '21BCE3780',
        domains: ['management'],
        status: 'committee',
    },
    {
        name: 'Varun ',
        username: 'Varun_0361',
        regNo: '21BCE0361',
        domains: ['management'],
        status: 'core',
    },
    {
        name: 'Raghav Trivedi',
        username: 'RTrivedi17',
        regNo: '21BCE0417',
        domains: ['management'],
        status: 'core',
    },
    {
        name: 'Pratyaksh',
        username: 'poggers',
        regNo: '21BKT0092',
        domains: ['management'],
        status: 'core',
    },
    {
        name: 'Arushi Bawa',
        username: 'zizi',
        regNo: '21BCE3370',
        domains: ['management'],
        status: 'core',
    },
    {
        name: 'Sanvi Chavan',
        username: 'sanvi_c',
        regNo: '21BDS0166',
        domains: ['management'],
        status: 'core',
    },
    {
        name: 'Soha Jagtap',
        username: 'SohaJagtap',
        regNo: '21BML0091',
        domains: ['management'],
        status: 'core',
    },
    {
        name: 'Anubhav Aryan',
        username: 'anubhav08',
        regNo: '21BEC0726',
        domains: ['management'],
        status: 'core',
    },
    {
        name: 'Adya Sawhney',
        username: '_adya',
        regNo: '21BCE3391',
        domains: ['management'],
        status: 'core',
    },
    {
        name: 'Vaishnavi Rathod',
        username: 'Vaishnavi',
        regNo: '21BCB0191',
        domains: ['management'],
        status: 'core',
    },
    {
        name: 'Shubhi Shyamsukha',
        username: 'Shubhi1706',
        regNo: '21BCB0242',
        domains: ['management'],
        status: 'core',
    },
    {
        name: 'anushka',
        username: 'Anushka',
        regNo: '21BCE0516',
        domains: ['design'],
        status: 'committee',
    },
    {
        name: 'parth',
        username: 'parthdoesccsagain',
        regNo: '19BCE3322',
        domains: ['design'],
        status: 'committee',
    },
    {
        name: 'Shravani Rane',
        username: 'shravani_raney',
        regNo: '21BCE2910',
        domains: ['design'],
        status: 'committee',
    },
    {
        name: 'Satya Sundar Nayak',
        username: 'Satya1210',
        regNo: '21BCE0909',
        domains: ['design'],
        status: 'committee',
    },
    {
        name: 'Khushi Kauntia',
        username: 'khushi_28',
        regNo: '21BCT0096',
        domains: ['design'],
        status: 'committee',
    },
    {
        name: 'Rashmi M T',
        username: 'rashmi',
        regNo: '21BCE0174',
        domains: ['design'],
        status: 'committee',
    },
    {
        name: 'Aditya Vispute',
        username: 'aditya.vispute',
        regNo: '21BCI0031',
        domains: ['design'],
        status: 'committee',
    },
    {
        name: 'Aniket PERAI',
        username: 'aniket_perai',
        regNo: '21BEC0440',
        domains: ['design'],
        status: 'committee',
    },
    {
        name: 'ANKITA BEHERA',
        username: 'GLORY',
        regNo: '21BCE2913',
        domains: ['design'],
        status: 'committee',
    },
    {
        name: 'Arul Goyal',
        username: '21BCE2672',
        regNo: '21BCE2672',
        domains: ['design'],
        status: 'committee',
    },
    {
        name: 'Aryan Jain',
        username: 'aryanjain',
        regNo: '21BCE0186',
        domains: ['design'],
        status: 'committee',
    },
    {
        name: 'Gauransh Sharma',
        username: 'gauransh18',
        regNo: '21BCE0494',
        domains: ['design'],
        status: 'committee',
    },
    {
        name: 'Jeenia Gogoi',
        username: 'JehG',
        regNo: '21BEC0302',
        domains: ['design'],
        status: 'committee',
    },
    {
        name: 'Khushi Kauntia',
        username: 'khushi_28',
        regNo: '21BCT0096',
        domains: ['design'],
        status: 'committee',
    },
    {
        name: 'Medhansh Jain',
        username: 'MedhanshJain',
        regNo: '21BCB0183',
        domains: ['design'],
        status: 'committee',
    },
    {
        name: 'SHAIK MOHAMMED SUHAIL',
        username: 'ShaikSuhail',
        regNo: '21MIC0025',
        domains: ['design'],
        status: 'committee',
    },
    {
        name: 'Taneesha Kulshrestha',
        username: 'taneekul29',
        regNo: '21BCE2353',
        domains: ['design'],
        status: 'committee',
    },
    {
        name: 'Yuvraj',
        username: 'Singh',
        regNo: '21BCE0234',
        domains: ['design'],
        status: 'committee',
    },
    {
        name: 'Arjun Rajesh',
        username: 'arjun1903',
        regNo: '21BCE3663',
        domains: ['design'],
        status: 'core',
    },
    {
        name: 'Prakhar',
        username: 'prakhar965',
        regNo: '21BCE0579',
        domains: ['design'],
        status: 'core',
    },
    {
        name: 'Khushi Kauntia',
        username: 'khushi_28',
        regNo: '21BCT0096',
        domains: ['design'],
        status: 'core',
    },
    {
        name: 'Anushka Roy Chowdhury',
        username: 'anushka',
        regNo: '21BCE0256',
        domains: ['design'],
        status: 'core',
    },
    {
        name: 'Jatin Jakhar',
        username: 'jatinjakhar',
        regNo: '21BCE2511',
        domains: ['design'],
        status: 'core',
    },
    {
        name: 'Tia',
        username: 'TiaMartin',
        regNo: '21BCE3536',
        domains: ['design'],
        status: 'core',
    },
    {
        name: 'Sahil ',
        username: 'Chugh',
        regNo: '21BCE3585',
        domains: ['design'],
        status: 'core',
    },
    {
        name: 'Pratham Mishra',
        username: 'Pratham',
        regNo: '21BDS0133',
        domains: ['design'],
        status: 'core',
    },
    {
        name: 'Ashwin Ravikumar',
        username: 'E_Lucid_At0r',
        regNo: '21BEC0148',
        domains: ['design'],
        status: 'core',
    },
    {
        name: 'Aayushi Singh Thakur',
        username: 'Aayushisingh',
        regNo: '21BCB0195',
        domains: ['video'],
        status: 'committee',
    },
    {
        name: 'Aprupshri S R',
        username: 'aprupshri@gmail.com',
        regNo: '21BCE3078',
        domains: ['video'],
        status: 'committee',
    },
    {
        name: 'Pranjal Pratosh',
        username: 'pranjal_pratosh',
        regNo: '21BCE3291',
        domains: ['video'],
        status: 'committee',
    },
    {
        name: 'Pravinth V',
        username: 'Pravinth12',
        regNo: '21BEC2482',
        domains: ['tech'],
        status: 'committee',
    },
];
